scr/AmediaTestCrud.Web/Controllers/LoginController.cs
using AmediaTestCrud.Application.Intefaces.Services;
using AmediaTestCrud.Web.Models;
using AmediaTestCrud.Web.Models.UserContext;
using AmediaTestCrud.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace AmediaTestCrud.Web.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserService _userService;
        private readonly ICurrentUserContextService _currentUserContextService;

        public LoginController(IUserService userService, ICurrentUserContextService currentUserContextService)
            => (_userService, _currentUserContextService) = (userService, currentUserContextService);

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(LoginViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = await _userService.ValidateUser(model.UserName, model.Password);

                    _currentUserContextService.SetUser(new(user.Id, user.UserName, (UserRoles)user.RoleId));

                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }

            return View("Index");
        }

        public IActionResult Logout()
        {
            _currentUserContextService.RemoveUser();

            return View("Index");
        }
    }
}

scr/AmediaTestCrud.Web/Controllers/UserController.cs
using AmediaTestCrud.Application.Intefaces.Services;
using AmediaTestCrud.Domain.Entities;
using AmediaTestCrud.Web.Configurations.Attributes;
using AmediaTestCrud.Web.Models;
using AmediaTestCrud.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AmediaTestCrud.Web.Controllers;

[AuthorizeUserAttribute(Models.UserContext.UserRoles.Admin)]
public class UserController : Controller
{
    #region Atributos
    private readonly ICurrentUserContextService _currentUserContextService;
    private readonly IUserService _userService;
    private readonly IRoleService _roleService;

    public UserController(ICurrentUserContextService currentUserContextService,
                          IUserService userService,
                          IRoleService roleService)
    {
        _currentUserContextService = currentUserContextService;
        _userService = userService;
        _roleService = roleService;
    }
    #endregion

    #region Buscador
    public async Task<IActionResult> Index()
    {
        var users = await _userService.GetAll();
        var usersModel = users.Select(u => new UserViewModel()
        {
            UserId = u.Id,
            FirstName = u.FirstName,
            LastName = u.LastName,
            Role = u.Role.Description,
            Active = u.IsActive()
        }).ToList(); // Habría que usar automapper

        return View(usersModel);
    }
    #endregion

    #region Consultar
    public async Task<IActionResult> Details(int? id)
    {
        var user = await _userService.GetById(id.Value);
        if (user is null)
            return NotFound();

        var model = CreateUserViewModel(user);
        return View(model);
    }
    #endregion

    #region Nuevo
    public async Task<IActionResult> Create()
    {
        ViewData["Roles"] = new SelectList(await _roleService.GetForSelect(), "Id", "Description");
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(UserViewModel model)
    {
        try
        {
            if (ModelState.IsValid)
            {
                var user = new User(model.UserName, model.Password, model.FirstName, model.LastName, model.Document, model.RoleId, 1); //Automapper

                await _userService.Create(user);

                return RedirectToAction("Index");
            }
        }
        catch (Exception ex)
        {
            ViewBag.Error = ex.Message;
        }

        ViewData["Roles"] = new SelectList(await _roleService.GetForSelect(), "Id", "Description", model.RoleId);
        return View();
    }
    #endregion

    #region Modificar
    public async Task<IActionResult> Edit(int? id)
    {
        ViewData["Roles"] = new SelectList(await _roleService.GetForSelect(), "Id", "Description");
        var user = await _userService.GetById(id.Value);
        if (user is null)
            return NotFound();

        var model = CreateUserViewModel(user);
        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(UserViewModel model)
    {

        try
        {
            var user = await _userService.GetById(model.UserId);
            user.Update(model.UserName, model.FirstName, model.LastName, model.Document, model.RoleId, model.Active ? 1 : 0); //Automapper

            await _userService.Update(user);

            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            ViewBag.Error = ex.Message;
        }

        ViewData["Roles"] = new SelectList(await _roleService.GetForSelect(), "Id", "Description");
        return View(model);
    }

    public async Task<IActionResult> EditPassword(int? id)
    {
        var user = await _userService.GetById(id.Value);
        if (user is null)
            return NotFound();

        var model = new ChangePasswordViewModel() { UserId = user.Id };
        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditPassword(ChangePasswordViewModel model)
    {

        try
        {
            await _userService.UpdatePassword(model.UserId, model.OldPassword, model.NewPassword);

            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            ViewBag.Error = ex.Message;
        }

        return View(model);
    }
    #endregion

    #region Eliminar
    public async Task<IActionResult> Delete(int? id)
    {
        var user = await _userService.GetById(id.Value);
        if (user is null)
            return NotFound();

        var model = CreateUserViewModel(user);
        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(UserViewModel model)
    {

        try
        {
            var currentUser = _currentUserContextService.GetUser();
            if (currentUser.UserId == model.UserId)
                throw new Exception("No puede eliminarte a ti mismo");

            var user = await _userService.GetById(model.UserId);
            if (user is null)
                return NotFound();

            await _userService.Delete(model.UserId);

            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            ViewBag.Error = ex.Message;
        }

        return View(model);
    }
    #endregion

    #region Automapper
    private UserViewModel CreateUserViewModel(User user)
        => new UserViewModel()
        {
            UserId = user.Id,
            UserName = user.UserName,
            Password = user.Password,
            FirstName = user.FirstName,
            LastName = user.LastName,
            Document = user.Document,
            RoleId = user.RoleId,
            Role = user.Role.Description,
            Active = user.IsActive(),
        };
    #endregion
}

scr/AmediaTestCrud.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestCrud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AmediaTestCrud.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Administrar Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Cerrar sesión</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

scr/AmediaTestCrud.Web/Views/Shared/_LayoutDefault.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestCrud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AmediaTestCrud.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Cerrar sesión</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

scr/AmediaTestCrud.Web/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestCrud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AmediaTestCrud.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="Index">TestCrud</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>